name: Test

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04}
          - {os: ubuntu-22.04-arm}
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libmpfr-dev
          version: ${{ runner.os }}-${{ runner.arch }}-1.0
      - run: |
          cmake -S . -B build
          cmake --build build
          ./build/mpfr_test
